name: simplecloud-api
version: "1.0"
main: app.simplecloud.api.platform.spigot.SpigotApiProvider
api-version: "1.21"
folia-supported: true

libraries:
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0"
  - "org.jetbrains.kotlin:kotlin-stdlib:2.0.20"
  - "org.jetbrains.kotlin:kotlin-reflect:2.0.20"